from except_func import *

assert except_func() == "Got exception", "no exception got"
